-- Realtime is handled by the Hono WebSocket server plus PostgreSQL LISTEN/NOTIFY.
-- Run `database/realtime_notify_triggers.sql` to install NOTIFY triggers for the
-- curated table list used by `server/src/realtime.js`.
--
-- This file is kept as a compatibility pointer for older setup notes that used
-- to enable Supabase Realtime publications. Do not configure `supabase_realtime`
-- for the Hono/PostgreSQL backend.
